vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    partner_images:
      uri_prefix: /images/partner
      upload_destination: "%kernel.project_dir%/public/images/partner"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    structure_images:
      uri_prefix: /images/structure
      upload_destination: "%kernel.project_dir%/public/images/structure"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer